name: NuNuGet CI
on:
  pull_request:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '.editorconfig'
      - '.vscode/**'
      - '*.md'
  workflow_dispatch:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  build:
    name: Build
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: false
          fetch-depth: 0
          filter: blob:none

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Install .NET tools
        shell: pwsh
        run: |
          dotnet tool restore

      - name: Restore
        shell: pwsh
        run: |
          & dotnet restore

      # - name: Check formatting
      #   shell: pwsh
      #   run: |
      #     & dotnet format --no-restore --verify-no-changes

      # - name: Build (debug)
      #   shell: pwsh
      #   run: |
      #     & dotnet pack --no-restore --configuration Debug /bl:__artifacts/msbuild.debug.binlog

      # - name: Test (debug)
      #   shell: pwsh
      #   run: |
      #     & dotnet test --no-restore --configuration Debug

      - name: Build (release)
        shell: pwsh
        run: |
          & dotnet pack --no-restore --configuration Release /bl:__artifacts/msbuild.release.binlog

      - name: Test (release)
        shell: pwsh
        run: |
          & dotnet test --no-restore --configuration Release

      - name: Publish packages
#        if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/develop"]'), github.ref) }}
        shell: pwsh
        run: |
          & dotnet nuget add source --name github "https://nuget.pkg.github.com/mschofie/index.json"
          Get-ChildItem -Path __artifacts/package/release/MSchofie.*.nupkg |
            ForEach-Object {
              & dotnet nuget push $_.FullName --api-key ${{ secrets.PACKAGE_PUBLISH_PAT }} --source "github"
            }

      - name: Upload 'package' artifact
        uses: actions/upload-artifact@v6
        with:
          name: __artifacts_package
          path: |
            __artifacts/package

      - name: Upload 'msbuild_binlog' artifact
        uses: actions/upload-artifact@v6
        with:
          name: __artifacts_msbuild_binlog
          path: |
            __artifacts/msbuild.debug.binlog
            __artifacts/msbuild.release.binlog

  create-release:
    name: Create release and upload assets
    needs: build
    runs-on: ubuntu-slim
    permissions:
      contents: write
#    if: ${{ github.event_name == 'push' && contains(fromJSON('["refs/heads/main"]'), github.ref) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: false
          fetch-depth: 0
          filter: blob:none

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Install .NET tools
        shell: pwsh
        run: |
          dotnet tool restore

      - name: Download package artifact
        uses: actions/download-artifact@v7
        with:
          name: __artifacts_package
          path: __artifacts/package

      - name: Get version
        id: get_version
        shell: pwsh
        run: |
          # Since this build is only on 'main', use the 'NuGetPackageVersion' variant of the 'nbgv' version.
          # This will not include the build-identifiers in the version, which we want for a public release.
          $Version = (& dotnet nbgv get-version --variable NuGetPackageVersion)
          if (-not $Version) { Write-Error 'Version not found'; exit 1 }
          Add-Content -Path $env:GITHUB_OUTPUT -Value "version=$Version"

      - name: Create release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          $Version = $env:VERSION
          if (-not $Version) { Write-Error 'Version not found'; exit 1 }

          $RefName = if ('${{ github.ref }}' -match 'refs/heads/(.*)') { $Matches[1] }

          Write-Host "Logging into gh"
          Write-Output $env:GITHUB_TOKEN | gh auth login --with-token

          Write-Host "Creating draft release 'v$Version'"
          $Arguments = @(
            "v$Version"
            "--draft"
            if ($Version -match '-') {
              "--prerelease"
            }
            if ($RefName) {
              "--target", $RefName
            }
            "--title", "v$Version"
            "--notes", ""
            "--latest=false"
          )
          gh release create @Arguments

          $files = Get-ChildItem -Path '__artifacts/package/release/MSchofie.*.nupkg' -ErrorAction SilentlyContinue
          if (-not $files) { Write-Host "No .nupkg files found to upload"; exit 0 }
          foreach ($file in $files) {
            Write-Host "Uploading $($file.Name)"
            gh release upload "v$Version" $file.FullName --clobber
          }
